from pydantic import BaseModel, Field, field_validator


class ChatRequest(BaseModel):
    """
    Inbound user payload for the chat endpoint.
    Pydantic v2 enforces boundary validation before data reaches services.
    """
    message: str = Field(
        ...,
        min_length=1,
        max_length=4000,
        description="The user question or instruction to process",
        examples=["Explain how a Transformer neural network processes tokens."]
    )

    @field_validator("message")
    @classmethod
    def validate_not_empty_or_whitespace(cls, value: str) -> str:
        trimmed = value.strip()
        if not trimmed:
            raise ValueError("Message cannot be empty or purely whitespace.")
        return trimmed


class ChatResponse(BaseModel):
    """
    Validated response schema returned to the client.
    Guarantees consistent contract structure containing the model's generated answer and source model name.
    """
    answer: str = Field(
        ...,
        description="The synthesized answer generated by the foundational model"
    )
    model: str = Field(
        ...,
        description="The specific LLM identifier that produced this generation"
    )


class ErrorDetail(BaseModel):
    """
    Standardized API error response format for client consumption and Swagger documentation.
    """
    detail: str = Field(..., description="Human-readable description of what caused the failure")
    error_code: str = Field(..., description="Machine-readable error category for client branching")
